import os
import yaml
import pandas as pd
from datetime import datetime


def load_config(config_path="config.yaml"):
    with open(config_path, "r") as file:
        config = yaml.safe_load(file)
    return config


def main():

    # Load Configuration
    config = load_config()

    raw_path = config["data"]["raw_path"]
    processed_dir = config["data"]["processed_dir"]
    production_dir = config["data"]["production_dir"]
    manifest_path = config["data"]["manifest_path"]
    train_size = config["data"]["train_size"]
    drop_columns = config["data"]["drop_columns"]
    version = config["data"]["current_version"]

    print("Configuration loaded successfully.")

    # Load Raw Dataset
    print("Loading raw dataset...")
    df = pd.read_csv(raw_path)

    print(f"Raw dataset shape: {df.shape}")


    # Drop Leakage Columns and Onehot Encoding
    print("Dropping leakage columns...")
    df = df.drop(columns=drop_columns)
    print(f"Shape after dropping columns: {df.shape}")

    print("Encoding categorical columns...")
    df = pd.get_dummies(df, columns=["Type"], drop_first=True)
    print(f"Shape after encoding : {df.shape}")

    # Chronological Split
    print("Performing chronological split...")

    train_df = df.iloc[:train_size]
    production_df = df.iloc[train_size:]

    print(f"Train set shape: {train_df.shape}")
    print(f"Production set shape: {production_df.shape}")


    # Ensure Output Directories Exist
    os.makedirs(processed_dir, exist_ok=True)
    os.makedirs(production_dir, exist_ok=True)


    # Save Versioned Files
    train_path = os.path.join(processed_dir, f"{version}_train.csv")
    production_path = os.path.join(production_dir, f"{version}_production.csv")

    train_df.to_csv(train_path, index=False)
    production_df.to_csv(production_path, index=False)

    print("Versioned datasets saved successfully.")

    # Update Manifest Log
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    manifest_entry = f"""
Version: {version}
Timestamp: {timestamp}
Generated By Script: src/data_prep.py
Raw Dataset: {raw_path}
Train Dataset: {train_path}
Production Dataset: {production_path}
Dropped Columns: {drop_columns}
Encoding: One-hot encoding applied to 'Type' (drop_first=True)
Train Size: {train_size}
------------------------------------------------------------
"""


    with open(manifest_path, "a") as f:
        f.write(manifest_entry)

    print("Manifest updated successfully.")
    print("Data preparation completed successfully.")


if __name__ == "__main__":
    main()
